config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'users/create'
  post 'users/create'


  get 'users/show'

  get 'calculator/addition'
  post 'calculator/addition'

  get 'calculator/subtraction'

  get 'calculator/multiplication'

  get 'calculator/division'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'chapters/create'
  get 'authors/create'
  get 'contents/create'

  root 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
	def create
	end
end

app/controllers/calculator_controller.rb
class CalculatorController < ApplicationController
  def addition
  	@a = params[:a].to_i
  	@b = params[:b].to_i

  end

  def subtraction
  end

  def multiplication
  end

  def division
  end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
	layout 'my_layout'
	def create
		@name = "chapter one"
		@pages = 12
		@font = "Ariel"
		@size = 12

	end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
	layout 'authors'
	def create
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new

  end

  def create
  	#byebug

    @user = User.new(fname: params[:fname],lname: params[:lname],
            :dob => params[:dob], gender: params[:gender],
            :hobbies => params[:rock],qualification: params[:qualification])
    @user.save

  	@fullname = params[:fname] + params[:lname]
    @age = calculate_age(params[:dob])
  	@hobbies = params[:rock].join(",") if params[:rock]
  	@gender = params[:gender]
  	@qualification = params[:qualification]
  end

  def calculate_age(dob)
    def humanize secs
      [ 
        [60, :seconds], 
        [60, :minutes], 
        [24, :hours], 
        [365, :days], 
        [100, :years]
      ].map do |count, name|
        #byebug
        if secs > 0
          secs, n = secs.divmod(count)
          "#{n.to_i} #{name}"
        end
      end.compact.reverse.join(' ')
    end
    distance = Time.new - Time.parse(dob)
    humanize(distance).split(" ").take(4).join(",")
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculator_helper.rb
module CalculatorHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/calculator/addition.html.erb
<%= form_tag do %>

<p>Enter A value : <%= number_field_tag 'a', nil, in: 1...10, step: 2 %></p>
<p>Enter B value : <%= number_field_tag 'b' , nil, in: 1...10%></p>
<p><%= submit_tag "Addition" %></p>

<% end %>

<% if @a != nil %>
	<h1>Addition : <%= @a + @b %> </h1>
<% end %>

app/views/calculator/division.html.erb
<h1>Calculator#division</h1>
<p>Find me in app/views/calculator/division.html.erb</p>

app/views/calculator/multiplication.html.erb
<h1>Calculator#multiplication</h1>
<p>Find me in app/views/calculator/multiplication.html.erb</p>

app/views/calculator/subtraction.html.erb
<h1>Calculator#subtraction</h1>
<p>Find me in app/views/calculator/subtraction.html.erb</p>

app/views/chapters/create.html.erb
<h1><center>Chapters Create Page</center></h1>
<p> Name  : <%= @name %></p>
<p> Pages : <%= @pages %></p>
<p> Font  : <%= @font %></p>
<p> Size  : <%= @size %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notebook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <h1>Hi hello </h1>
    <%= yield %>
  </body>
</html>

app/views/layouts/authors.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notebook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <h1>Authors layout</h1>
    <%= yield %>
  </body>
</html>

app/views/layouts/my_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notebook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <h1>My layout </h1>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<p>Name : <%= @fullname %></p>
<p>age  : <%= @age %></p>
<p>Hobbies : <%= @hobbies %></p>
<p>Gender  :  <%= @gender %></p>
<p>Qualification : <%= @qualification %></p>

<p>
	<%= link_to "New User",  users_new_url %>
</p>

app/views/users/new.html.erb
<h1><center>User Form</center></h1>
<%= form_tag('/users/create') do %>
	<p>
		<%= label_tag 'firstname' %>
		<%= text_field_tag 'fname' %>
	</p>
	<p>
		<%= label_tag 'lastname' %>
		<%= text_field_tag 'lname' %>
	</p>
	<p>
		<%= label_tag 'DOB' %>
		<%= date_field_tag 'dob' %>
	</p>
	<p>
		<%= label_tag 'gender' %>
		<%= radio_button_tag 'gender', 'male'%> Male
		<%= radio_button_tag 'gender', 'female' %> Female
	</p>
	<p>
		<%= label_tag 'hobbies' %><br/>
		<%= check_box_tag 'rock[]', 'cricket' %> Cricket
		<%= check_box_tag 'rock[]', 'hocky' %> Hocky
		<%= check_box_tag 'rock[]', 'football' %> football
		<%= check_box_tag 'rock[]', 'vollyball' %> volly ball
	</p>
	<p>
		<%= label_tag "qualification" %>
		<%= select_tag "qualification", "<option>MCA</option><option>Btech</option><option>B.com</option>".html_safe , include_blank: true%> 	
	</p>
	<p>
		<%= submit_tag %>
	</p>
<% end %>

<%= @data %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>